# Generated by Django 5.2.8 on 2026-02-19 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenom', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('biographie', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='auteurs/')),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('date_deces', models.DateField(blank=True, null=True)),
                ('nationalite', models.CharField(blank=True, max_length=100)),
                ('site_web', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Auteur',
                'verbose_name_plural': 'Auteurs',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Editeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('site_web', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Éditeur',
                'verbose_name_plural': 'Éditeurs',
            },
        ),
        migrations.CreateModel(
            name='Langue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icone', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='catalogue.categorie')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True)),
                ('sous_titre', models.CharField(blank=True, max_length=300)),
                ('description', models.TextField()),
                ('isbn', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('couverture', models.ImageField(blank=True, null=True, upload_to='couvertures/')),
                ('fichier', models.FileField(upload_to='livres/')),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'ePub'), ('mobi', 'Mobi')], default='pdf', max_length=10)),
                ('taille_fichier', models.PositiveIntegerField(blank=True, help_text='Taille en Ko', null=True)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('nombre_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('publie', 'Publié'), ('brouillon', 'Brouillon'), ('archive', 'Archivé')], default='publie', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('nombre_telechargements', models.PositiveIntegerField(default=0)),
                ('nombre_lectures', models.PositiveIntegerField(default=0)),
                ('auteurs', models.ManyToManyField(related_name='livres', to='catalogue.auteur')),
                ('categories', models.ManyToManyField(related_name='livres', to='catalogue.categorie')),
                ('editeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livres', to='catalogue.editeur')),
                ('langue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogue.langue')),
            ],
            options={
                'verbose_name': 'Livre',
                'verbose_name_plural': 'Livres',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('valide', models.BooleanField(default=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to=settings.AUTH_USER_MODEL)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='catalogue.livre')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-date_creation'],
                'unique_together': {('livre', 'utilisateur')},
            },
        ),
    ]
