# Generated by Django 5.2.8 on 2026-02-19 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogue', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_minutes', models.PositiveIntegerField(default=0)),
                ('pages_lues', models.PositiveIntegerField(default=0)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='catalogue.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de lecture',
                'verbose_name_plural': 'Sessions de lecture',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='ListeLecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Ma liste', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('publique', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listes_lecture', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Liste de lecture',
                'verbose_name_plural': 'Listes de lecture',
            },
        ),
        migrations.CreateModel(
            name='LivreDansListe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('note_personnelle', models.TextField(blank=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('lu', models.BooleanField(default=False)),
                ('liste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lecture.listelecture')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogue.livre')),
            ],
            options={
                'ordering': ['ordre'],
                'unique_together': {('liste', 'livre')},
            },
        ),
        migrations.AddField(
            model_name='listelecture',
            name='livres',
            field=models.ManyToManyField(related_name='listes', through='lecture.LivreDansListe', to='catalogue.livre'),
        ),
        migrations.CreateModel(
            name='Signet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField()),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('note', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signets', to='catalogue.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Signet',
                'verbose_name_plural': 'Signets',
                'ordering': ['page'],
            },
        ),
        migrations.CreateModel(
            name='Favori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_en_favoris', to='catalogue.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoris', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favori',
                'verbose_name_plural': 'Favoris',
                'ordering': ['-date_ajout'],
                'unique_together': {('utilisateur', 'livre')},
            },
        ),
        migrations.CreateModel(
            name='Progression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_courante', models.PositiveIntegerField(default=1)),
                ('pourcentage', models.FloatField(default=0.0)),
                ('derniere_lecture', models.DateTimeField(auto_now=True)),
                ('termine', models.BooleanField(default=False)),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='catalogue.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression',
                'verbose_name_plural': 'Progressions',
                'unique_together': {('utilisateur', 'livre')},
            },
        ),
    ]
